// Package git contains the constrained host-side Git operations required by
// the Phase 1 clone/import lifecycle.
package git

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	codegenboxRemote = "codegenbox-source"
	workspaceRefRoot = "refs/heads/codegenbox/"
)

var ErrDirtyClone = errors.New("session clone became dirty before cleanup")

// Repository is the Git state captured before a session starts.
type Repository struct {
	Root       string
	BaseBranch string
	BaseCommit string
}

// Discover identifies the enclosing repository and captures its current HEAD.
func Discover(ctx context.Context, directory string) (Repository, error) {
	root, err := run(ctx, directory, "rev-parse", "--show-toplevel")
	if err != nil {
		return Repository{}, fmt.Errorf("discover Git repository from %q: %w", directory, err)
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return Repository{}, fmt.Errorf("resolve repository root: %w", err)
	}
	root, err = filepath.Abs(root)
	if err != nil {
		return Repository{}, fmt.Errorf("make repository root absolute: %w", err)
	}

	branch, err := run(ctx, root, "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return Repository{}, fmt.Errorf("read Git base branch: %w", err)
	}
	commit, err := run(ctx, root, "rev-parse", "HEAD")
	if err != nil {
		return Repository{}, fmt.Errorf("read Git base commit: %w", err)
	}
	if err := validateOID(commit); err != nil {
		return Repository{}, fmt.Errorf("validate Git base commit: %w", err)
	}

	return Repository{
		Root:       filepath.Clean(root),
		BaseBranch: branch,
		BaseCommit: commit,
	}, nil
}

// CreateSessionClone makes an independent clone whose complete Git directory
// is within workspace. It intentionally does not retain a remote back to the
// source repository: Docker mounts only this clone, not the source repository.
func CreateSessionClone(ctx context.Context, repositoryRoot, workspace, branch, baseCommit string) error {
	if err := validateSessionBranch(branch); err != nil {
		return err
	}
	if err := validateOID(baseCommit); err != nil {
		return fmt.Errorf("invalid base commit: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(workspace), 0o700); err != nil {
		return fmt.Errorf("create clone parent: %w", err)
	}
	if _, err := os.Lstat(workspace); err == nil {
		return fmt.Errorf("session workspace already exists: %s", workspace)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect session workspace %q: %w", workspace, err)
	}

	// --no-local prevents Git's local-clone optimization; --no-hardlinks makes
	// the intent explicit for Git versions where a local transport is available.
	// --no-checkout prevents clone-time checkout hooks from running.
	if _, err := runAt(ctx, "", "clone", "--no-local", "--no-hardlinks", "--no-checkout", "--no-tags", "--origin", codegenboxRemote, "--", repositoryRoot, workspace); err != nil {
		return fmt.Errorf("create independent session clone: %w", err)
	}

	// The branch exists only in the clone until post-exit import. This prevents
	// an agent from touching a source-repository ref while it is running.
	if _, err := run(ctx, workspace, "checkout", "--no-track", "-b", branch, baseCommit); err != nil {
		return fmt.Errorf("start clone on session branch: %w", err)
	}
	// A fresh clone deliberately has no host Git identity. A harmless local
	// identity lets an agent use ordinary `git commit` without exposing host
	// configuration or credentials; agents may replace it in their clone.
	if _, err := run(ctx, workspace, "config", "--local", "user.name", "Codegenbox"); err != nil {
		return fmt.Errorf("configure clone commit identity: %w", err)
	}
	if _, err := run(ctx, workspace, "config", "--local", "user.email", "codegenbox@localhost"); err != nil {
		return fmt.Errorf("configure clone commit email: %w", err)
	}
	if _, err := run(ctx, workspace, "remote", "remove", codegenboxRemote); err != nil {
		return fmt.Errorf("remove source remote from session clone: %w", err)
	}
	if _, err := validateCloneLayout(workspace); err != nil {
		return fmt.Errorf("validate independent session clone: %w", err)
	}
	return nil
}

// IsDirty reports whether the workspace has tracked or untracked changes. It
// does not read the agent-writable clone config while it inspects the clone.
func IsDirty(ctx context.Context, workspace string) (bool, error) {
	gitDir, err := validateCloneLayout(workspace)
	if err != nil {
		return false, err
	}
	status, err := withQuarantinedConfig(gitDir, func() (string, error) {
		return runInClone(ctx, gitDir, workspace, "status", "--porcelain=v1", "--untracked-files=all")
	})
	if err != nil {
		return false, fmt.Errorf("inspect clone status: %w", err)
	}
	return status != "", nil
}

// ImportSessionBranch imports only branch from the independent clone. The
// expected branch and base are generated by Codegenbox; no clone config,
// remote, tag, agent-selected ref, or hook participates in the import.
//
// The policy is deliberately narrow: the imported commit must be baseCommit
// itself or a descendant of it. The source ref is atomically created only if
// absent, so main, tags, and unrelated branches cannot be changed here.
func ImportSessionBranch(ctx context.Context, repositoryRoot, workspace, branch, baseCommit, expectedImportedCommit, dataRoot string) (string, error) {
	if err := validateSessionBranch(branch); err != nil {
		return "", err
	}
	if err := validateOID(baseCommit); err != nil {
		return "", fmt.Errorf("invalid recorded base commit: %w", err)
	}
	gitDir, err := validateCloneLayout(workspace)
	if err != nil {
		return "", fmt.Errorf("validate session clone before import: %w", err)
	}

	// Read only the fixed, host-generated branch rather than HEAD. Quarantining
	// config also prevents a clone-controlled include, fsmonitor, or hook path
	// from influencing trusted host-side inspection.
	commit, err := withQuarantinedConfig(gitDir, func() (string, error) {
		commit, err := runInClone(ctx, gitDir, workspace, "rev-parse", "--verify", "--end-of-options", workspaceRef(branch)+"^{commit}")
		if err != nil {
			return "", fmt.Errorf("read expected clone branch: %w", err)
		}
		if err := validateOID(commit); err != nil {
			return "", fmt.Errorf("validate expected clone commit: %w", err)
		}
		allowed, err := isAncestorInClone(ctx, gitDir, workspace, baseCommit, commit)
		if err != nil {
			return "", err
		}
		if !allowed {
			return "", fmt.Errorf("import policy rejected %s: it is not %s or a descendant", commit, baseCommit)
		}
		return commit, nil
	})
	if err != nil {
		return "", err
	}

	bundle, cleanupBundle, err := bundlePath(dataRoot)
	if err != nil {
		return "", err
	}
	defer cleanupBundle()
	if _, err := withQuarantinedConfig(gitDir, func() (string, error) {
		return runInClone(ctx, gitDir, workspace, "bundle", "create", bundle, workspaceRef(branch))
	}); err != nil {
		return "", fmt.Errorf("export expected clone branch: %w", err)
	}

	// Fetching an explicit bundle ref copies objects only. --no-write-fetch-head
	// and --no-tags prevent transient or agent-created refs from landing in the
	// source repository.
	if _, err := run(ctx, repositoryRoot, "fetch", "--no-tags", "--no-write-fetch-head", "--no-recurse-submodules", bundle, workspaceRef(branch)); err != nil {
		return "", fmt.Errorf("import clone objects: %w", err)
	}
	if _, err := run(ctx, repositoryRoot, "cat-file", "-e", commit+"^{commit}"); err != nil {
		return "", fmt.Errorf("verify imported commit: %w", err)
	}
	allowed, err := isAncestor(ctx, repositoryRoot, baseCommit, commit)
	if err != nil {
		return "", err
	}
	if !allowed {
		return "", fmt.Errorf("import policy rejected %s: it is not %s or a descendant", commit, baseCommit)
	}

	// A missing ImportedCommit can only create a new reserved branch. On resume,
	// the recorded imported OID is the exact compare-and-swap old value; this
	// never force-updates an unrelated or externally changed source ref.
	expected := strings.Repeat("0", len(commit))
	if expectedImportedCommit != "" {
		if err := validateOID(expectedImportedCommit); err != nil {
			return "", fmt.Errorf("invalid recorded imported commit: %w", err)
		}
		expected = expectedImportedCommit
	}
	if _, err := run(ctx, repositoryRoot, "update-ref", workspaceRef(branch), commit, expected); err != nil {
		return "", fmt.Errorf("atomically advance reserved session branch: %w", err)
	}
	return commit, nil
}

// ValidateSessionClone verifies the independent clone layout without reading
// clone-controlled configuration. It is used before a retained clone is resumed.
func ValidateSessionClone(workspace string) error {
	_, err := validateCloneLayout(workspace)
	return err
}

// RemoveSessionClone removes only a clone that the caller has already found
// clean and successfully imported. The layout and Codegenbox session-root
// containment are checked again so cleanup cannot escape owned storage.
func RemoveSessionClone(dataRoot, workspace string) error {
	sessionRoot, err := filepath.EvalSymlinks(filepath.Join(dataRoot, "sessions"))
	if err != nil {
		return fmt.Errorf("resolve session storage before removal: %w", err)
	}
	workspace, err = filepath.Abs(workspace)
	if err != nil {
		return fmt.Errorf("resolve clean session clone: %w", err)
	}
	workspace = filepath.Clean(workspace)
	if !isWithin(workspace, sessionRoot) {
		return fmt.Errorf("refuse to remove clone outside Codegenbox session storage: %s", workspace)
	}
	if _, err := validateCloneLayout(workspace); err != nil {
		return fmt.Errorf("validate clean session clone before removal: %w", err)
	}
	// This is deliberately the last operation before removal. Lifecycle's
	// earlier status checks decide import/state; this check prevents a local
	// writer in the remaining interval from losing uncommitted work.
	dirty, err := IsDirty(context.Background(), workspace)
	if err != nil {
		return fmt.Errorf("final clean-clone status check: %w", err)
	}
	if dirty {
		return fmt.Errorf("%w: %s", ErrDirtyClone, workspace)
	}
	if err := os.RemoveAll(workspace); err != nil {
		return fmt.Errorf("remove clean session clone: %w", err)
	}
	if _, err := os.Lstat(workspace); !os.IsNotExist(err) {
		if err == nil {
			return fmt.Errorf("clean session clone still exists after removal: %s", workspace)
		}
		return fmt.Errorf("inspect removed session clone: %w", err)
	}
	return nil
}

func isWithin(path, parent string) bool {
	relative, err := filepath.Rel(parent, path)
	if err != nil {
		return false
	}
	return relative == "." || (relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)))
}

func workspaceRef(branch string) string {
	return workspaceRefRoot + strings.TrimPrefix(branch, "codegenbox/")
}

func validateSessionBranch(branch string) error {
	if !strings.HasPrefix(branch, "codegenbox/") {
		return fmt.Errorf("invalid session branch %q", branch)
	}
	id := strings.TrimPrefix(branch, "codegenbox/")
	if id == "" || strings.Contains(id, "/") || strings.Contains(id, "..") {
		return fmt.Errorf("invalid session branch %q", branch)
	}
	if (id[0] < 'a' || id[0] > 'z') && (id[0] < '0' || id[0] > '9') {
		return fmt.Errorf("invalid session branch %q", branch)
	}
	for _, character := range id {
		if (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '-' {
			return fmt.Errorf("invalid session branch %q", branch)
		}
	}
	return nil
}

func validateOID(oid string) error {
	if len(oid) != 40 && len(oid) != 64 {
		return fmt.Errorf("unexpected object ID %q", oid)
	}
	for _, character := range oid {
		if (character < '0' || character > '9') && (character < 'a' || character > 'f') {
			return fmt.Errorf("unexpected object ID %q", oid)
		}
	}
	return nil
}

func validateCloneLayout(workspace string) (string, error) {
	workspace, err := filepath.Abs(workspace)
	if err != nil {
		return "", fmt.Errorf("resolve workspace: %w", err)
	}
	workspace = filepath.Clean(workspace)
	info, err := os.Lstat(workspace)
	if err != nil {
		return "", fmt.Errorf("inspect workspace: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return "", fmt.Errorf("workspace is not an ordinary directory: %s", workspace)
	}

	gitDir := filepath.Join(workspace, ".git")
	info, err = os.Lstat(gitDir)
	if err != nil {
		return "", fmt.Errorf("inspect clone Git directory: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return "", fmt.Errorf("clone .git is not an ordinary directory")
	}
	if err := filepath.WalkDir(gitDir, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("clone Git directory contains symlink %q", path)
		}
		return nil
	}); err != nil {
		return "", err
	}
	if _, err := os.Lstat(filepath.Join(gitDir, "objects", "info", "alternates")); err == nil {
		return "", fmt.Errorf("clone Git directory uses object alternates")
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("inspect clone object alternates: %w", err)
	}
	// A commondir file turns an otherwise ordinary .git directory into a linked
	// worktree that may reach a host-side administrative directory. A Phase 1
	// session must always remain a standalone repository.
	if _, err := os.Lstat(filepath.Join(gitDir, "commondir")); err == nil {
		return "", fmt.Errorf("clone Git directory uses a shared common directory")
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("inspect clone common directory: %w", err)
	}
	return gitDir, nil
}

// withQuarantinedConfig temporarily removes the clone's local config while a
// trusted host operation reads its objects or index. It is restored even on
// error, and validation rejects symlinks before this is called.
func withQuarantinedConfig(gitDir string, operation func() (string, error)) (result string, err error) {
	config := filepath.Join(gitDir, "config")
	if _, statErr := os.Lstat(config); os.IsNotExist(statErr) {
		return operation()
	} else if statErr != nil {
		return "", fmt.Errorf("inspect clone config: %w", statErr)
	}

	temporary, err := os.CreateTemp(gitDir, ".codegenbox-config-")
	if err != nil {
		return "", fmt.Errorf("create clone config quarantine: %w", err)
	}
	temporaryPath := temporary.Name()
	if err := temporary.Close(); err != nil {
		os.Remove(temporaryPath)
		return "", fmt.Errorf("close clone config quarantine: %w", err)
	}
	if err := os.Remove(temporaryPath); err != nil {
		return "", fmt.Errorf("prepare clone config quarantine: %w", err)
	}
	if err := os.Rename(config, temporaryPath); err != nil {
		return "", fmt.Errorf("quarantine clone config: %w", err)
	}
	defer func() {
		restoreErr := os.Rename(temporaryPath, config)
		if restoreErr != nil {
			err = errors.Join(err, fmt.Errorf("restore clone config: %w", restoreErr))
		}
	}()
	return operation()
}

func runInClone(ctx context.Context, gitDir, workspace string, args ...string) (string, error) {
	prefix := []string{"--git-dir=" + gitDir, "--work-tree=" + workspace}
	return runAt(ctx, "", append(prefix, args...)...)
}

func isAncestorInClone(ctx context.Context, gitDir, workspace, ancestor, descendant string) (bool, error) {
	return isAncestorWithArgs(ctx, "", []string{"--git-dir=" + gitDir, "--work-tree=" + workspace}, ancestor, descendant)
}

func isAncestor(ctx context.Context, repositoryRoot, ancestor, descendant string) (bool, error) {
	return isAncestorWithArgs(ctx, repositoryRoot, nil, ancestor, descendant)
}

func isAncestorWithArgs(ctx context.Context, directory string, prefix []string, ancestor, descendant string) (bool, error) {
	args := append([]string{}, prefix...)
	args = append(args, "merge-base", "--is-ancestor", ancestor, descendant)
	_, err := runAt(ctx, directory, args...)
	if err == nil {
		return true, nil
	}
	var exitError *exec.ExitError
	if errors.As(err, &exitError) && exitError.ExitCode() == 1 {
		return false, nil
	}
	return false, fmt.Errorf("validate import ancestry: %w", err)
}

func bundlePath(dataRoot string) (string, func(), error) {
	directory := filepath.Join(dataRoot, "imports")
	if err := os.MkdirAll(directory, 0o700); err != nil {
		return "", nil, fmt.Errorf("create import directory: %w", err)
	}
	temporary, err := os.CreateTemp(directory, ".session-import-*.bundle")
	if err != nil {
		return "", nil, fmt.Errorf("create import bundle path: %w", err)
	}
	path := temporary.Name()
	if err := temporary.Close(); err != nil {
		os.Remove(path)
		return "", nil, fmt.Errorf("close import bundle path: %w", err)
	}
	if err := os.Remove(path); err != nil {
		return "", nil, fmt.Errorf("prepare import bundle path: %w", err)
	}
	return path, func() { _ = os.Remove(path) }, nil
}

func run(ctx context.Context, directory string, args ...string) (string, error) {
	return runAt(ctx, directory, args...)
}

func runAt(ctx context.Context, directory string, args ...string) (string, error) {
	commandArgs := []string{"-c", "core.hooksPath=/dev/null", "-c", "core.fsmonitor=false", "-c", "core.untrackedCache=false"}
	if directory != "" {
		commandArgs = append(commandArgs, "-C", directory)
	}
	commandArgs = append(commandArgs, args...)
	cmd := exec.CommandContext(ctx, "git", commandArgs...)
	cmd.Env = safeGitEnvironment()
	output, err := cmd.CombinedOutput()
	if err != nil {
		message := strings.TrimSpace(string(output))
		if message == "" {
			return "", err
		}
		return "", fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, message)
	}
	return strings.TrimSpace(string(output)), nil
}

func safeGitEnvironment() []string {
	environment := make([]string, 0, len(os.Environ())+3)
	for _, entry := range os.Environ() {
		name, _, _ := strings.Cut(entry, "=")
		if strings.HasPrefix(name, "GIT_") {
			continue
		}
		environment = append(environment, entry)
	}
	environment = append(environment,
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_CONFIG_GLOBAL=/dev/null",
		"GIT_TERMINAL_PROMPT=0",
	)
	return environment
}
